### ISSUE TITLE
Couple problems

### ISSUE THREAD

**Issue by nwmqpa** [ronanboiteau/NormEZ#13]
Hello, i've figured out four small problems in your Norme.
First of, when -- (Or ++, or ^ ...) is surrended by other chars (in a commentary ofc), your Norme detect it as an error.
The second that I'm running in, is the use of this sentence
```c
var[0]++;
```
In third position, the printf function, while being detected as an error, enclose also the my_printf function which is also declared as an error, as every other line containing the word printf inside, commented or not.
Which, while being correct, is detcted as an error.
Finally, the last error that happens to me is the several assignements on the same line that happens with : 
```c
write(2, ": \033[1;36m", 9);
```

**Comment by ronanboiteau** [comment]
Issues 1, 3 and 4: NormEZ doesn't make the difference between strings/comments & code. 

Issue 2: fixed by commit [617849db2114b759f8b2092bcf1dc32e02e5717e](https://github.com/ronanboiteau/NormEZ/commit/617849db2114b759f8b2092bcf1dc32e02e5717e).

Issue 3: `my_printf()` should not be flagged, only `prinft()`, do you have a code sample that I could use to reproduce this bug?
